/**
 * @file Auto-generated theme definitions
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Edit scripts/themes-catalog.json and run: bun run generate:theme-registry
 */

export type NodeEditorThemeId =
  | "default"
  | "adobe"
  | "adobe-light"
  | "akzidenz-grotesk"
  | "antigravity"
  | "apple"
  | "blueprint"
  | "brutalist"
  | "constructivist"
  | "cursor"
  | "figma"
  | "github"
  | "github-light"
  | "google"
  | "macintosh"
  | "meta"
  | "minecraft"
  | "notion"
  | "opal"
  | "russian-avant-garde"
  | "stellar"
  | "unity"
  | "vaporwave"
  | "vscode"
  | "wargames"
  | "window98"
  | "windows31"
  | "windows11"
  | "windowsxp"
  | "xcorp";

export type NodeEditorTheme = {
  id: NodeEditorThemeId;
  label: string;
  description: string;
  cssPath: string;
};

export const GENERATED_THEMES: NodeEditorTheme[] = [
  {
    id: "default",
    label: "Default",
    description: "Modern defaults with rounded cards and soft shadows.",
    cssPath: "",
  },
  {
    id: "adobe",
    label: "Adobe",
    description: "Sleek dark interface inspired by Adobe Creative Cloud with refined blue accents.",
    cssPath: "/themes/adobe.css",
  },
  {
    id: "adobe-light",
    label: "Adobe Light",
    description: "Clean light interface inspired by Adobe Creative Cloud with refined blue accents.",
    cssPath: "/themes/adobe-light.css",
  },
  {
    id: "akzidenz-grotesk",
    label: "Akzidenz-Grotesk",
    description: "Swiss Style minimalism with strict grids and neutral typography.",
    cssPath: "/themes/akzidenz-grotesk.css",
  },
  {
    id: "antigravity",
    label: "Antigravity",
    description: "Deep space aesthetic with neon accents and glassmorphism effects.",
    cssPath: "/themes/antigravity.css",
  },
  {
    id: "apple",
    label: "Apple",
    description: "Translucent layers, spacious typography, and vibrant blue accent inspired by apple.com.",
    cssPath: "/themes/apple.css",
  },
  {
    id: "blueprint",
    label: "Blueprint",
    description: "Technical drawing style with grid lines, white-on-blue, and architectural aesthetics.",
    cssPath: "/themes/blueprint.css",
  },
  {
    id: "brutalist",
    label: "Brutalist",
    description: "Raw, bold aesthetic with hard shadows and high contrast.",
    cssPath: "/themes/brutalist.css",
  },
  {
    id: "constructivist",
    label: "Constructivist",
    description: "Avant-garde Russian art style with bold geometry and revolutionary red.",
    cssPath: "/themes/constructivist.css",
  },
  {
    id: "cursor",
    label: "Cursor",
    description: "Cursor-inspired dark theme with crisp surfaces and vibrant green accents.",
    cssPath: "/themes/cursor.css",
  },
  {
    id: "figma",
    label: "Figma",
    description: "Clean light interface with Figma's signature blue and minimal design language.",
    cssPath: "/themes/figma.css",
  },
  {
    id: "github",
    label: "GitHub Dark",
    description: "Dark dimmed look with desaturated neutrals and punchy blue call-to-action.",
    cssPath: "/themes/github.css",
  },
  {
    id: "github-light",
    label: "GitHub Light",
    description: "Clean light theme with GitHub's signature blue and subtle shadows.",
    cssPath: "/themes/github-light.css",
  },
  {
    id: "google",
    label: "Google",
    description: "Light, friendly surfaces with bold primary accent and Material-inspired shapes.",
    cssPath: "/themes/google.css",
  },
  {
    id: "macintosh",
    label: "Macintosh",
    description: "Classic 1984 Macintosh System 1.0 with pure black & white 1-bit aesthetic.",
    cssPath: "/themes/macintosh.css",
  },
  {
    id: "meta",
    label: "Meta",
    description: "Facebook/Meta design with clean blues, rounded corners, and friendly UI.",
    cssPath: "/themes/meta.css",
  },
  {
    id: "minecraft",
    label: "Minecraft",
    description: "Pixel-crafted UI with earthy neutrals and vibrant emerald highlight.",
    cssPath: "/themes/minecraft.css",
  },
  {
    id: "notion",
    label: "Notion",
    description: "Clean, minimalist workspace with crisp typography and subtle borders.",
    cssPath: "/themes/notion.css",
  },
  {
    id: "opal",
    label: "Opal",
    description: "Soft pastel aesthetic with gentle purples, warm cream surfaces, and flowing connections.",
    cssPath: "/themes/opal.css",
  },
  {
    id: "russian-avant-garde",
    label: "Russian Avant-Garde",
    description: "Suprematist composition with floating geometry and primary colors.",
    cssPath: "/themes/russian-avant-garde.css",
  },
  {
    id: "stellar",
    label: "Stellar",
    description: "Gray background with dark cards, warm orange accents, and clean flat design.",
    cssPath: "/themes/stellar.css",
  },
  {
    id: "unity",
    label: "Unity",
    description: "Professional dark theme with Unity's signature blue accent and flat panel design.",
    cssPath: "/themes/unity.css",
  },
  {
    id: "vaporwave",
    label: "V A P O R W A V E",
    description: "A E S T H E T I C neon pink & cyan with synthwave sunset grid and glitch effects.",
    cssPath: "/themes/vaporwave.css",
  },
  {
    id: "vscode",
    label: "VS Code",
    description: "Dark code editor theme with precise geometry and VS Code's signature blue.",
    cssPath: "/themes/vscode.css",
  },
  {
    id: "wargames",
    label: "WarGames",
    description: "CRT terminal with glowing green phosphor wireframes inspired by WOPR and DEFCON.",
    cssPath: "/themes/wargames.css",
  },
  {
    id: "window98",
    label: "Windows 98",
    description: "Pixel-perfect nostalgia with flat widgets and crisp blue chrome.",
    cssPath: "/themes/window98.css",
  },
  {
    id: "windows31",
    label: "Windows 3.1",
    description: "Classic 3D beveled UI with navy title bars and Program Manager aesthetics.",
    cssPath: "/themes/windows31.css",
  },
  {
    id: "windows11",
    label: "Windows 11",
    description: "Soft acrylic surfaces, centered layouts, and fluent blue accent of modern Windows.",
    cssPath: "/themes/windows11.css",
  },
  {
    id: "windowsxp",
    label: "Windows XP",
    description: "Blissful gradients, bold blues, and playful glass buttons from the XP era.",
    cssPath: "/themes/windowsxp.css",
  },
  {
    id: "xcorp",
    label: "X",
    description: "High-contrast dark theme with electric blue highlights and glassy surfaces.",
    cssPath: "/themes/xcorp.css",
  },
];
