/**
 * @file Default settings: keyboard
 */
import type { SettingDefinition } from "../types";

export const keyboardSettings = [
  {
    key: "keyboard.undo",
    label: "Undo",
    description: "Keyboard shortcut for undo",
    category: "keyboard",
    type: "text",
    defaultValue: "Ctrl+Z",
    pattern: "^(Ctrl\\+|Cmd\\+|Alt\\+|Shift\\+)*[A-Za-z0-9]+$",
    order: 1,
  },
  {
    key: "keyboard.redo",
    label: "Redo",
    description: "Keyboard shortcut for redo",
    category: "keyboard",
    type: "text",
    defaultValue: "Ctrl+Y",
    pattern: "^(Ctrl\\+|Cmd\\+|Alt\\+|Shift\\+)*[A-Za-z0-9]+$",
    order: 2,
  },
  {
    key: "keyboard.selectAll",
    label: "Select All",
    description: "Keyboard shortcut for select all",
    category: "keyboard",
    type: "text",
    defaultValue: "Ctrl+A",
    pattern: "^(Ctrl\\+|Cmd\\+|Alt\\+|Shift\\+)*[A-Za-z0-9]+$",
    order: 3,
  },
  {
    key: "keyboard.delete",
    label: "Delete",
    description: "Keyboard shortcut for delete",
    category: "keyboard",
    type: "text",
    defaultValue: "Delete",
    order: 4,
  },
  {
    key: "keyboard.copy",
    label: "Copy",
    description: "Keyboard shortcut for copy",
    category: "keyboard",
    type: "text",
    defaultValue: "Ctrl+C",
    pattern: "^(Ctrl\\+|Cmd\\+|Alt\\+|Shift\\+)*[A-Za-z0-9]+$",
    order: 5,
  },
  {
    key: "keyboard.paste",
    label: "Paste",
    description: "Keyboard shortcut for paste",
    category: "keyboard",
    type: "text",
    defaultValue: "Ctrl+V",
    pattern: "^(Ctrl\\+|Cmd\\+|Alt\\+|Shift\\+)*[A-Za-z0-9]+$",
    order: 6,
  },
  {
    key: "keyboard.duplicate",
    label: "Duplicate",
    description: "Keyboard shortcut for duplicate",
    category: "keyboard",
    type: "text",
    defaultValue: "Ctrl+D",
    pattern: "^(Ctrl\\+|Cmd\\+|Alt\\+|Shift\\+)*[A-Za-z0-9]+$",
    order: 7,
  },
  {
    key: "keyboard.group",
    label: "Group",
    description: "Keyboard shortcut for group nodes",
    category: "keyboard",
    type: "text",
    defaultValue: "Ctrl+G",
    pattern: "^(Ctrl\\+|Cmd\\+|Alt\\+|Shift\\+)*[A-Za-z0-9]+$",
    order: 8,
  },
  {
    key: "keyboard.save",
    label: "Save",
    description: "Keyboard shortcut for save",
    category: "keyboard",
    type: "text",
    defaultValue: "Ctrl+S",
    pattern: "^(Ctrl\\+|Cmd\\+|Alt\\+|Shift\\+)*[A-Za-z0-9]+$",
    order: 9,
  },
] as const satisfies readonly SettingDefinition[];

